version: '3' 

services:
  # ----------------- #
  #    Apache Spark   #
  # ----------------- #
  spark-master:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-master
    hostname: spark-master
    ports:
      - 9090:8080
      - 7077:7077
    env_file:
      - spark_master.env
    volumes:
      - ./data:/data
      - ./src:/src

  spark-worker:
    image: docker.io/bitnami/spark:3.3
    container_name: spark-worker
    hostname: spark-worker
    ports:
      - 8081:8081
    env_file:
      - spark_worker.env
    volumes:
      - ./data:/data
      - ./src:/src

  # ----------------- #
  #        Kafka      #
  # ----------------- #

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    container_name: zookeeper
    volumes:
      - "zookeeper_data:/bitnami"
    env_file:
      - zookeeper.env
    ports:
      - 22181:2181

  kafka:
    image: docker.io/bitnami/kafka:3.3
    container_name: kafka
    volumes:
      - "kafka_data:/bitnami"
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    env_file:
      - kafka.env

  kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: kafka-ui
    ports:
      - 18080:8080
    restart: "always"
    env_file:
      - kafka_ui.env
    depends_on:
      - kafka
      - zookeeper

  # namenode:
  #   image: bde2020/hadoop-namenode:1.1.0-hadoop2.8-java8
  #   container_name: namenode
  #   hostname: namenode
  #   environment:
  #     - CLUSTER_NAME=test
  #     # - CORE_CONF_fs_defaultFS=hdfs://namenode:9000
  #   env_file:
  #     - hadoop.env
  #   ports:
  #     # - 9000:9000
  #     - 50070:50070

  # datanode:
  #   image: bde2020/hadoop-datanode:1.1.0-hadoop2.8-java8
  #   container_name: datanode
  #   hostname: datanode
  #   environment:
  #     SERVICE_PRECONDITION: namenode:50070
  #     # CORE_CONF_fs_defaultFS: hdfs://namenode:9000
  #   env_file:
  #     - hadoop.env
  #   ports:
  #     # - 9001:9001
  #     - 50075:50075

  # resourcemanager:
  #   image: bde2020/hadoop-resourcemanager:2.0.0-hadoop2.7.4-java8
  #   container_name: resourcemanager
  #   hostname: resourcemanager
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
  #   env_file:
  #     - hadoop.env
  
volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  # hive-server:
  #   image: bde2020/hive:2.3.2-postgresql-metastore
  #   container_name: hive-server
  #   hostname: hive-server
  #   env_file:
  #     - hadoop.env
  #   # depends_on:
  #   #   - namenode
  #   environment:
  #     HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
  #     SERVICE_PRECONDITION: "hive-metastore:9083"
  #   ports:
  #     - 10000:10000

  # hive-metastore:
  #   image: bde2020/hive:2.3.2-postgresql-metastore
  #   container_name: hive-metastore
  #   hostname: hive-metastore
  #   env_file:
  #     - hadoop.env
  #   command: /opt/hive/bin/hive --service metastore
  #   environment:
  #     SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088"
  #   ports:
  #     - 9083:9083

  # hive-metastore-postgresql:
  #   image: bde2020/hive-metastore-postgresql:2.3.0
  #   container_name: hive-metastore-postgresql
  #   hostname: hive-metastore-postgresql
  #   environment:
  #     - POSTGRES_DB = db
  #     - POSTGRES_USER=user
  #     - POSTGRES_PASSWORD=admin
  #   ports:
  #     - 5432:5432

  # presto-coordinator:
  #   image: shawnzhu/prestodb:0.181
  #   container_name: presto-coordinator
  #   hostname: presto-coordinator
  #   ports:
  #     - 8080:8080

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   hostname: pgadmin
  #   ports:
  #     - 5050:80
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: post@gres.com
  #     PGADMIN_DEFAULT_PASSWORD: admin

  # hue:
  #   image: bde2020/hdfs-filebrowser:3.11
  #   container_name: hue
  #   hostname: hue
  #   environment:
  #       SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083"
  #   ports:
  #     - 8088:8088
  #   depends_on:
  #     - hive-metastore-postgresql
  #   environment:
  #     - NAMENODE_HOST=namenode

  # huedb:
  #   image: postgres:12.1-alpine
  #   volumes:
  #     - pg_data:/var/lib/postgresl/data/
  #   ports:
  #     - "5432"
  #   env_file:
  #     - ./hadoop-hive.env
  #   environment:
  #       SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432 resourcemanager:8088 hive-metastore:9083"
